dump_borrowck_info=false
log_dir = "./log"
output_dir = "./rust_proofs"
run_check = false
admit_proofs = false
skip_unsupported_features = false
extra_specs = "./extra_specs.v"
generate_dune_project = false
lib_load_paths = ["./refinedrust/stdlib/", "./rust_proofs"]
trust_debug = true
